# Netlify Build Ayarları
[build]
  command = "npm run build" # Projeyi inşa etmek için kullanılacak komut
  publish = "dist"          # İnşa edilen dosyaların bulunduğu klasör

# Single Page Application (SPA) için Yönlendirme Kuralları
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200